version: '3.8'
services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./dockerfiles/user_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
  goweb:
    build: 
      context: .
      dockerfile: dockerfiles/WebDockerfile
    ports:
      - '3001:3001'
    environment:
      USER_SERV_GRPC: user:50055
      JWT_SECRET: 80023b32850d760e786f0957b13fdc6cf2b96e9b5afb397752607f533725672e
      JWT_EXPIRATION_HOURS: 72h
      PORT: 3001
    # volumes:
    #   - ./.volumes/web:/app
  user:
    build: 
      context: .
      dockerfile: dockerfiles/UserDockerfile
    ports:
      - '50055:50055'
    environment:
      USER_DB_HOST: db
      USER_DB_PORT: 5432
      USER_DB_USER: postgres
      USER_DB_PASSWORD: postgres
      USER_DB_NAME: user
      DB_SSL_MODE: disable
      PORT: 50055
    depends_on:
      - db
    # volumes:
    #   - ./.volumes/user:/app
volumes:
  db:
    driver: local