version: '3.8'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: postgres:16.1
    # command: ["postgres", "-c", "log_statement=all"]
    # uncomment this if u wanna output all SQL queries to the console
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    # environment:
    #   POSTGRES_DB: mydatabase
    #   POSTGRES_USER: myuser
    #   POSTGRES_PASSWORD: mypassword
    restart: always

volumes:
  postgres_data: